#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : patsy
Version  : 0.5.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/8b/c7/c3f6ae21cd9bde9b434ffc5a451e2ba657a5a062d21ee41fe9990c739013/patsy-0.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/8b/c7/c3f6ae21cd9bde9b434ffc5a451e2ba657a5a062d21ee41fe9990c739013/patsy-0.5.0.tar.gz
Summary  : A Python package for describing statistical models and for building design matrices.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: patsy-python3
Requires: patsy-license
Requires: patsy-python
Requires: ipython
Requires: jsonschema
Requires: mistune
Requires: numpy
Requires: pandas
Requires: scipy
Requires: six
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
(especially linear models, or models that have a linear component) and
        building design matrices. Patsy brings the convenience of `R

%package license
Summary: license components for the patsy package.
Group: Default

%description license
license components for the patsy package.


%package python
Summary: python components for the patsy package.
Group: Default
Requires: patsy-python3

%description python
python components for the patsy package.


%package python3
Summary: python3 components for the patsy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the patsy package.


%prep
%setup -q -n patsy-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530978524
find -name "*pyx" | xargs touch ||:
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/patsy
cp LICENSE.txt %{buildroot}/usr/share/doc/patsy/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/patsy/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
